// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file ImageRequest.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _IMAGEREQUEST_H_
#define _IMAGEREQUEST_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ImageRequest_SOURCE)
#define ImageRequest_DllAPI __declspec( dllexport )
#else
#define ImageRequest_DllAPI __declspec( dllimport )
#endif // ImageRequest_SOURCE
#else
#define ImageRequest_DllAPI
#endif
#else
#define ImageRequest_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

/*!
 * @brief This class represents the structure ImageMessage defined by the user in the IDL file.
 * @ingroup IMAGEREQUEST
 */
class ImageMessage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ImageMessage();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ImageMessage();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ImageMessage that will be copied.
     */
    eProsima_user_DllExport ImageMessage(const ImageMessage &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ImageMessage that will be copied.
     */
    eProsima_user_DllExport ImageMessage(ImageMessage &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ImageMessage that will be copied.
     */
    eProsima_user_DllExport ImageMessage& operator=(const ImageMessage &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ImageMessage that will be copied.
     */
    eProsima_user_DllExport ImageMessage& operator=(ImageMessage &&x);

    /*!
     * @brief This function sets a value in member remote_time
     * @param _remote_time New value for member remote_time
     */
    inline eProsima_user_DllExport void remote_time(int64_t _remote_time)
    {
        m_remote_time = _remote_time;
    }

    /*!
     * @brief This function returns the value of member remote_time
     * @return Value of member remote_time
     */
    inline eProsima_user_DllExport int64_t remote_time() const
    {
        return m_remote_time;
    }

    /*!
     * @brief This function returns a reference to member remote_time
     * @return Reference to member remote_time
     */
    inline eProsima_user_DllExport int64_t& remote_time()
    {
        return m_remote_time;
    }
    /*!
     * @brief This function sets a value in member seq
     * @param _seq New value for member seq
     */
    inline eProsima_user_DllExport void seq(int32_t _seq)
    {
        m_seq = _seq;
    }

    /*!
     * @brief This function returns the value of member seq
     * @return Value of member seq
     */
    inline eProsima_user_DllExport int32_t seq() const
    {
        return m_seq;
    }

    /*!
     * @brief This function returns a reference to member seq
     * @return Reference to member seq
     */
    inline eProsima_user_DllExport int32_t& seq()
    {
        return m_seq;
    }
    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    inline eProsima_user_DllExport void data(const std::vector<char> &_data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    inline eProsima_user_DllExport void data(std::vector<char> &&_data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    inline eProsima_user_DllExport const std::vector<char>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    inline eProsima_user_DllExport std::vector<char>& data()
    {
        return m_data;
    }

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const ImageMessage& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    int64_t m_remote_time;
    int32_t m_seq;
    std::vector<char> m_data;
};

#endif // _IMAGEREQUEST_H_